  # Give the first play a name.
  # The plays ensures that updates are installed on the system. It also installs
  # a .MSU package on the systems.
- name: Manage updates on systems
  # Indicate the hosts to target for this play
  hosts: all
  # Indicate the variables for this play:
  vars:
    log_file: C:\Windows\Temp\ansible_available_updates.txt
    KB: 'KB4465065'
    access_token: ""
  tasks:
    - name: Microsoft update servers are queried
      win_updates:
        category_names: SecurityUpdates
        state: searched
        log_path: "{{ log_file }}"

    - name: Available security updates are captured
      win_shell: "type {{ log_file }}"
      register: file_output


    - name: Available updates found
      debug:
        msg: "Available updates found!"
      when: "'Adding update' in file_output.stdout"

    - name: MSU package is retrieved on hosts
      win_uri:
        url: >
          https://gitlab.example.com/student/updates/raw/master/files/{{ KB }}.msu
        dest: C:\Windows\Temp\{{ KB }}.msu
        validate_certs: no
        force_basic_auth: yes
        method: GET
        headers:
          PRIVATE-TOKEN: "{{ access_token }}"

    - name: MSU package is installed
      win_hotfix:
        hotfix_kb: "{{ KB }}"
        source: C:\Windows\Temp\{{ KB }}.msu
        state: present

    - name: Security updates are applied
      win_updates:
        category_name:
          - Updates
        whitelist:
          - KB4494174
          - KB4346084
      register: updates_status
  
    - name: Server is rebooted
      win_reboot:
      when: updates_status.reboot_required


  # Give the second play a name
  # The plays invokes Chocolatey to install a set of packages to install
  # packages on the server.
- name: Install packages on systems
  hosts: all
  
  vars:
    packages:
      - Putty
      - Wireshark

  tasks:
    - name: Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Packages are installed
      win_chocolatey:
        name: "{{ packages }}"
        state: present
        pinned: true
      register: install_result

    - name: Server is rebooted
      win_reboot:
      when: install_result.changed and install_result.rc == 3010