---
- name: Configure login message
  hosts: win1.example.com
  vars:
    message_key: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'

  tasks:
    - name: Configure login message caption
      win_regedit:
        path: '{{ message_key }}'
        name: CHANGE_ME
        data: 'Hello!'
        type: string

    - name: Configure login message text
      win_regedit:
        path: '{{ message_key }}'
        name: CHANGE_ME
        data: >
          'Welcome to the {{ CHANGE_ME }}({{ CHANGE_ME }}) system.
          This system is running {{ CHANGE_ME }}, and has
          {{ CHANGE_ME }} cpu/s and {{ CHANGE_ME }} MiB of RAM.'
        type: string
